site_name: Perfect CommonLisp
theme: material
markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Lisp開発環境セットアップ:
    - Environments/Windows.md
  - Lispの学習:
    - Learning/hello-world.md
